### ISSUE TITLE
Awesome package but why have you promoted version 2 to php >=5.5.0

### ISSUE THREAD

**Issue by drnkwati** [avplab/php-html-builder#1]
Hi 
I went through you source code but never noticed any php 5.5.0 features or functions.
Apart from the short array syntax added in php 5.4.
Are my missing something?
I wish to recommend you adjust this php version to support to 5.4.0 and if possible revert the array syntax so we can use this in 5.3 projects as well.
This will encourage more developers to use this package.
I could fork the project and make these adjustments for my personal use, but i consider it a waste

**Comment by avplab** [comment]
Hi, thanks! It makes sense. 
I've updated the package to support php5.3+. 
[avplab/php-html-builder v2.0.1](https://github.com/avplab/php-html-builder/tree/v2.0.1) was released.
